# .streamlit/secrets.toml
# Secret key for the DB Server
[connections.sql_server]
driver = "{ODBC Driver 17 for SQL Server}" # <--- ADICIONAR ESTA LINHA
server = "tcp:gongalves-server.database.windows.net,1433"
database = "GestaoHoras"
uid = "SusanaGongalves"
pwd = "Certifique-se que esta é a sua palavra-passe real!"