[connections.sql_server]
driver = "{ODBC Driver 17 for SQL Server}"
server = "tcp:gestaohoras-server-susana-goncalves.database.windows.net,1433"
database = "GestaoHoras"
uid = "Susanavgoncalves"
pwd = "Joninh@s2022" # A sua palavra-passe real foi inserida aqui